<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AssemblyName>BasicSample</AssemblyName>
    <RootNamespace>BasicSample</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="prometheus-net.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
  </ItemGroup>

  <ItemGroup Condition="'$(ValidateNupkg)' != 'true'">
    <ProjectReference Include="..\..\src\Kestrel.PathTrace\Kestrel.PathTrace.csproj" />
    <ProjectReference Include="..\..\src\Kestrel.PathTrace.Prometheus\Kestrel.PathTrace.Prometheus.csproj" />
    <ProjectReference Include="..\..\src\Kestrel.PathTrace.OpenTelemetry\Kestrel.PathTrace.OpenTelemetry.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(ValidateNupkg)' == 'true'">
    <PackageReference Include="Kestrel.PathTrace" />
    <PackageReference Include="Kestrel.PathTrace.OpenTelemetry" />
    <PackageReference Include="Kestrel.PathTrace.Prometheus" />
  </ItemGroup>

</Project>
