<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Kestrel.PathTrace.Tests.Prometheus</AssemblyName>
    <RootNamespace>Kestrel.PathTrace.Tests.Prometheus</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Assertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kestrel.PathTrace.Prometheus\Kestrel.PathTrace.Prometheus.csproj" />
  </ItemGroup>

</Project>
